events {}

http {
  server {
    listen 8080;

    location /api/auth/ {
      proxy_pass http://node-auth-svc:3000/;
    }

    location /api/employees/ {
      proxy_pass http://employee-svc:3000/;
    }

    location /api/attendance/ {
      proxy_pass http://attendance-svc:3000/;
    }

    location /api/leave/ {
      proxy_pass http://leave-svc:3000/;
    }

    location /api/reports/ {
      proxy_pass http://report-svc:3000/;
    }

    location /api/notifications/ {
      proxy_pass http://notification-svc:3000/;
    }

    location /health {
      return 200 'OK';
      add_header Content-Type text/plain;
    }
  }
}